---
abstract: 'process XSLT 2.0 using Saxon 9.x'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.021, CPAN::Meta::Converter version 2.140640'
keywords:
  - Java
  - 'XSL transformations'
  - XSLT
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Saxon-XSLT2
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  XML::Saxon::XSLT2:
    file: lib/XML/Saxon/XSLT2.pm
    version: '0.009'
requires:
  Inline::Java: '0'
  XML::LibXML: '1.60'
  perl: '5.008000'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/XML-Saxon-XSLT2/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-Saxon-XSLT2
  homepage: https://metacpan.org/release/XML-Saxon-XSLT2
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-xml-saxon-xslt2.git
version: '0.009'
x_contributors:
  - TOBYINK
