---
abstract: 'process XSLT 2.0 using Saxon 9.x'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Java
  - 'XSL transformations'
  - XSLT
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XML::Saxon::XSLT2
name: XML-Saxon-XSLT2
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Inline::Java: 0
  XML::LibXML: 1.60
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-Saxon-XSLT2
  homepage: https://metacpan.org/release/XML-Saxon-XSLT2
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-xml-saxon-xslt2
version: 0.007
